apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-frontend
  template:
    metadata:
      labels:
        app: job-frontend
    spec:
      containers:
        - name: frontend
          image: sambitmass/demo:job-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: job-frontend
spec:
  selector:
    app: job-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: manually set the external port (must be between 30000–32767)
